files: '.*warnings_stacklevel|tests'
exclude: '^.*(docs)'
repos:
  - repo: meta
    hooks:
      - id: identity
  - repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
      - id: black
        args: [--safe, --quiet, --line-length=120]
        language_version: python3.8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: check-builtin-literals
      - id: check-json
      - id: check-merge-conflict
      - id: forbid-submodules
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
  - repo: .
    rev: d4d36ecc34a94fdfd4642bd9ae5087c2b686fc78
    hooks:
      - id: warnings_stacklevel